### ISSUE TITLE
Vibe is broken

### ISSUE THREAD

**Issue by Octelly** [pragtical/plugins#6]
Hey, I'm new to Pragtical and Lite. Just chipping in that Vibe doesn't seem to be working anymore

```
Error: ...lly/.config/pragtical/plugins/lite-xl-vibe/interface.lua:94: attempt to get length of field 'project_files' (a nil value)

stack traceback:
    ...lly/.config/pragtical/plugins/lite-xl-vibe/interface.lua:94: in function 'get_items'
    /usr/share/pragtical/core/statusview.lua:850: in function 'update_active_items'
    /usr/share/pragtical/core/statusview.lua:1169: in function 'update'
    /usr/share/pragtical/core/node.lua:509: in function 'update'
    /usr/share/pragtical/core/node.lua:517: in function 'update'
    /usr/share/pragtical/core/node.lua:517: in function 'update'
    /usr/share/pragtical/core/node.lua:517: in function 'update'
    /usr/share/pragtical/core/node.lua:517: in function 'update'
    ...
    /usr/share/pragtical/plugins/contextmenu.lua:27: in function 'root_view_update'
    /usr/share/pragtical/plugins/treeview.lua:607: in function 'update'
    /usr/share/pragtical/core/init.lua:1258: in function 'step'
    /usr/share/pragtical/core/init.lua:1371: in function 'core_run'
    /usr/share/pragtical/plugins/settings.lua:1943: in function 'core_run'
    /usr/share/pragtical/plugins/ipc.lua:851: in function 'run'
    ....config/pragtical/plugins/lite-xl-vibe/vibeworkspace.lua:343: in function 'run'
    [string "local core..."]:15: in function <[string "local core..."]:6>
    [C]: in function 'xpcall'
    [string "local core..."]:6: in main chunk
```

**Comment by jgmdev** [comment]
Pragtical incorporates various changes for better performance on projects that contain many files. These changes would require the vibe plugin to be adjusted in order to support pragtical by checking which core properties are available eg: https://github.com/juliardi/lite-xl-treeview-extender/pull/1/files#diff-9fb5c6cd715e2651c8602e943a4a44c131f82d1b8fffeb61b06f3f3ba693e10f.

The new `projects` interface can be seen here:
https://github.com/pragtical/pragtical/blob/master/data/core/project.lua

Also the newly introduced core functions for handling projects can be seen here:
https://github.com/pragtical/pragtical/blob/master/data/core/init.lua

**Comment by Willem3141** [comment]
I just came across Pragtical and installed it, then came across [this FAQ entry](https://pragtical.dev/docs/about/faq#vim-mode) telling me to install Vibe if I wanted a Vim mode, however this indeed doesn't work:

```sh
> data/plugins/plugin_manager/ppm.x86_64-linux install vibe
can't find dependency lite-xl-vibe
```

If no working Vim mode plugin is currently available, it would be nice to adapt the FAQ entry and/or remove the plugin from the list, as right now new users that want a Vim mode just get a confusing error.

**Comment by jgmdev** [comment]
Forked and ported vibe plugin my self to work with pragtical newer projects API here https://github.com/pragtical/vibe. It should provide the modal editing experience some people desires. Added a note to the repo since I don't plan to maintain it, hopefully someone comes with a simpler modal editing plugin that doesn't adds much over the original editor experience and just focuses on modal editing. For the moment this plugin should do.

P.S. The plugin should now be installable from the plugin manager but running the `Plugin Manager: Purge` command would be necessary before  opening the plugin browser or running `Plugin Manager: Show`.
